"""them rang buoc cho hashtag va product

Revision ID: 1661a898a7e0
Revises: 7ceb0de611f0
Create Date: 2025-11-27 15:18:28.514732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1661a898a7e0'
down_revision = '7ceb0de611f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_hashtags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('product_hashtags_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('product_hashtags_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'hash_tags', ['hashtag_id'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_hashtags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_hashtags_ibfk_1'), 'hash_tags', ['hashtag_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('product_hashtags_ibfk_2'), 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
