"""update product and related tables

Revision ID: 407494e2650b
Revises: a4d3495b79a8
Create Date: 2025-10-30 18:13:06.624721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407494e2650b'
down_revision = 'a4d3495b79a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
