"""add column image_url to model.hash_tag

Revision ID: 7ceb0de611f0
Revises: 9d6c6f4b9ea7
Create Date: 2025-11-27 11:46:16.582355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ceb0de611f0'
down_revision = '9d6c6f4b9ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hash_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hash_tags', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
