"""add entity to order model

Revision ID: 88ea435b8d56
Revises: becdfd4aee30
Create Date: 2025-12-14 19:48:38.655412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88ea435b8d56'
down_revision = 'becdfd4aee30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('payos_order_code', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['payos_order_code'])
        batch_op.create_unique_constraint(None, ['order_code'])
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', mysql.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('payment_method')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('note')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('full_name')
        batch_op.drop_column('payos_order_code')
        batch_op.drop_column('order_code')

    # ### end Alembic commands ###
