"""update orderItem model

Revision ID: 9f0c5dca143e
Revises: 88ea435b8d56
Create Date: 2025-12-15 17:24:10.969853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0c5dca143e'
down_revision = '88ea435b8d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flavor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gift_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('product_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('flavor_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gift_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'gifts', ['gift_id'], ['id'])
        batch_op.create_foreign_key(None, 'product_flavors', ['flavor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('image_url')
        batch_op.drop_column('gift_name')
        batch_op.drop_column('flavor_name')
        batch_op.drop_column('product_name')
        batch_op.drop_column('gift_id')
        batch_op.drop_column('flavor_id')

    # ### end Alembic commands ###
