"""update product and related tables

Revision ID: a4d3495b79a8
Revises: a2f0ee48049f
Create Date: 2025-10-30 18:09:56.203613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4d3495b79a8'
down_revision = 'a2f0ee48049f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_flavors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('flavor_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('discount_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('origin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sold_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['sku'])
        batch_op.create_foreign_key(None, 'brands', ['brand_id'], ['id'])
        batch_op.drop_column('img_url')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('sold_count')
        batch_op.drop_column('rating')
        batch_op.drop_column('origin')
        batch_op.drop_column('weight')
        batch_op.drop_column('discount_percent')
        batch_op.drop_column('brand_id')
        batch_op.drop_column('sku')

    op.drop_table('product_flavors')
    op.drop_table('brands')
    # ### end Alembic commands ###
