"""Add email and total_spent to User

Revision ID: bd6a1a8a604a
Revises: af067bb72a05
Create Date: 2025-11-06 10:39:54.515996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6a1a8a604a'
down_revision = 'af067bb72a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('total_spent')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
