"""update cart model

Revision ID: becdfd4aee30
Revises: f3f84e215c18
Create Date: 2025-12-12 20:02:50.015097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becdfd4aee30'
down_revision = 'f3f84e215c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flavor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gift_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'product_flavors', ['flavor_id'], ['id'])
        batch_op.create_foreign_key(None, 'gifts', ['gift_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('gift_id')
        batch_op.drop_column('flavor_id')

    # ### end Alembic commands ###
