"""add gift model

Revision ID: f3f84e215c18
Revises: 1661a898a7e0
Create Date: 2025-12-07 12:16:23.770519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f84e215c18'
down_revision = '1661a898a7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_gifts',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('gift_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('product_id', 'gift_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_gifts')
    op.drop_table('gifts')
    # ### end Alembic commands ###
